Zocha:  Karczma wymieciona, nie bałaganić mi tu! 
Josabelle:  http://www.youtube.com/watch?v<br />\n=jKdn3xGCnsw&feature=player_em 
Narrator:   *Dni, które mijają powoli. Kiedy jest smutno. I inne, które upływają zbyt szybko. Kiedy jest radośnie. Dni w stanie zawieszenia, które oznajmiają nadejście czegoś nowego. Kilka dni poźniej. Wszystko jest jaśniejsze, nawet niebo wydaje się bardziej błękitne. Także główna świątynia nabiera barw i kolorów. Przyozdobiona prostymi lampionami i bratkami symbolizującymi nadzieję. I ten nagły tłum, pojawiający się znikąd. Otaczający kapłanki ubrane w białe szaty, niosące zapalone świece, których kroki zmierzają w stronę kaplicy gdzie odbyć się ma to niezwykłe wydarzenie - ślub namiestnika Ulver\\  a z hrabiną Zarnon*  
Deomi Vivianey:  a moge cos napisac czy musze tylko patrzec? 
Josabelle:  możesz pisac :) 
Deomi Vivianey:  moge cos tu pisac czy mam tylko patrzec? ;p 
Josabelle:  bedzie to chyba porazka :( 
Josabelle:  kiepsko to widze jak nikt sie nie udziela :( 
Naneth Ulver:  napisz im w szepcie, ze kazdfy mzoę pisac Doemi sie pytała ale nei miałam jak jej odpowiedziec bo pisałam posta;/ 
Naneth Ulver:  Tak.. nadzieja, wiara mi miłość. Cóż za obłuda i głupota. No ale kontrakt zawarła, wiec w końcu dojśc do tego musiało. Przeto właśnie wiązać miała los swój z człowiekiem, który był jej karą, nie nadzieją. Uniosła głowę patrząc przed siebie. Ludzi nie było wielu, to i lepiej. Nie musiała się starać aż tak bardzo. Całe szczęście żałoba  po parze Cesarskiej oszczędzi jej owej jakże rozkosznej zabawy u boku małżonka. Patrzyć na niego nie mogła, wiec tym lepiej że tak ustalono datę. Ot odbębni co trzeba i nie będzie musiała go ogladać. Westchenie uniosło jej pełne piersi delikatnie uwydatnione krojem prostej, leeganckiej sukni w kolorze bieli i srebra. Nie ona ja wybrała, ale przyznac musiała, iż krawcowa trafiła w jej gusta, nie czyniac z niej naszpikowanej błyskotkami poczwary. Delikatne, drobne perły mieniące się  lekko różem znalazły się machinalnie w jej smukłej dłoni., kiedy przekroczyła wielkie wrota świątyni . Nie będę o tym myśleć.. Ot raz i już.. uspakajała się w myślach odganiając szydercze szepty demonicznych sił. Krok za krokiem pokonywała drogę do miejsca, które miało być miejscem jej kaźni. Skupiła uwage na detalach, dziekujac kapłance w duchu za to, że przynajmniej stworzyła pozory.. Piekne miejsce, delikatny zapach kwiatów nadziei, świece i ta cudna muzyka.. Tak mógłby wygfladac jej slub z ukochanym meżczyzną. I wygladał, choc ostatni element był raczej nieadekwatny do dziecięcych marzeń sprzed lat. Ot, każdemu może się zdarzyć. 
Goinnoll:   *Mnich podpierał jedną, że ścian kaplicy. Z zaciekawieniem obserwował przygotowania do ślubu. Zaszedł tu przypadkiem, jednak stwierdził, że zostanie na dłużej. Cóż, ślub namiestnika było wydarzeniem, które warto było obejrzeć. Tak, więc podpierał swoją ścianę, jego czarne szaty wyglądały na czyste, mimo że było na nich kilka załatanych dziur, głowę miał jak zwykle ogoloną na łyso. I co dziwne, nie miał butów. Stał, myślał i uśmiechał się jak idiota. *  
Josabelle:  pisalam jej ale znikla 
Narrator:    *Później. Wnętrze świątyni.  Gdy wszycy goście i młodzi zajęli swoje miejsca. Zjawia się ona Najwyższa Kapłanka, przyodziana w złoto-białą szatę z diadem na głowie, pomalowana henną, która będzie przewodniczyć całej ceremonii. *  
Roinaven Ulver:   *Miało nie być świadków. To miało być ciche i szybkie. Tak by wielu nie oglądało i nie pamiętało tego dnia porażki Roinavena. Niestety. Rodzice jego przyszłej żony musieli się bardzo cieszyć z powodu pozbycia się potworka z domu. Wcale się im nie dziwił, ale jemu do śmiechu nie było. Urzędowa formalność. Nic ponad to. Stał już przy ołtarzu i czekał, tak jak nakazuje tradycja czy coś innego na co również nigdy nie zwracał uwagi. Dziś jednak musiał. Miejmy to już za sobą. Westchnął poprawiajac po raz ostatni żałobne.. znaczy odświetne odzienie. Zaraz się zacznie. *   
Josabelle:   *Wolnym krokiem zbliżyła się do ołtarza. Odmówiła krótką modlitwę po czym zwracając się do zebranych rzekła*  Witam wszystkich zgromadzonych. Zebraliśmy się tutaj aby połączyć węzłem małżeńskim hrabinę Naneth Zernon oraz namiestnika Roinaven\\  a Uverl\\  a. Jeśli ktoś zna powód, dla którego to małżeństwo nie mogłoby zostać zawarte niech przemówi teraz lub zamilknie na wieki! 
Naneth Ulver:   *całe szczescie nikt nei widział,z e na niego nie patrzyła. No przecież nie wypadało by panna młoda zahaftowała  podłogę świątyni na widok narzeczonego. Welon zasłaniał jej twarz , zaś wzrok skupiała na kapłance z nadzieja, że to nie potrwa długo.  *  
Roinaven Ulver:   *Błagam, niech ktoś przemówi... Niestety widział że to się stanie. *  - Witaj skarbie, pięknie dziś wyglądasz.  * Szepnął do Naneth nawet na nią nie patrząc. Wcale nie był przy tym złośliwy czy tam cyniczny. *  
Goinnoll:   *Mnich obserwował nic nie mówiąc. Bo, po co? Nie chciał przeszkadzać. Z uwagą słuchał słów kapłanki, czekając na ciąg dalszy. Czuł się jak intruz, nawet nie znał tych dwoje, więc… Rozejrzał się czekając na to aż ktoś przeszkodzi. Zastanawiał się czy taki precedens miał kiedyś miejsce.*  
Naneth Ulver:   *Ja ! krzyczała jej swiadomośc, jednak zacisniete zeby nie pozwoliły wydobys sie tym słowom z jej ust. Cały Niebyt smiał się w jej głowie lizac zuchwałymi językami jej jestestwo i poddając myśli o tym, że ślub jest początkiem a czeka ją noc poślubną no i resztę życia.  Jego szept wprawił ją w cyniczny nastrój..*  Wybacz najdroższy ale nie odwdzięczę się. Po prostu nie mam ochoty na ciebi patrzeć.. * odszepnęła mu z lekkim , cynicznym uśmiechem unoszącym jej usta pod delikatna materia welonu.*  
Josabelle:   *Rozejrzała się po sali po czym spojrzała na parę i delikatnie się uśmiechnęła*  Skoro nie ma przeciwwskazań przejdźmy dalej  *rzekła po czym skinieniem dłoni przywołała jedną z kapłanek która podeszła do Naneth i założyła jej na głowę pięknie upleciony wianek a następnie stanęła przy mównicy i zaczęła czytać*  
Roinaven Ulver:  - Nie będziesz musiała. Zaraz po tej uroczystej ceremonii wyjeżdżam na Wybrzeże. Niestety, wielce nad tym ubolewam, noc poślubną spędzisz sama.  * kontynuował nie zwracając najmniejszej uwagi na kapłanke czy zebranych gości. Zresztą miał pewność że nikt ich nie słyszy, a z daleko musi to i tak niewinnie wyglądać. *  - ... Albo wyśle ci mojego stajennego. Słyszałem że wpadłaś mu w oko.   
Josabelle:  szlak bot nie działa 
Naneth Ulver:  spróbuj jeszce raz albo napis zpo prostu ze tak kapłanka wyszła i cos tam czyta:) 
Lher Hanrid:   *No szukała go po całym mieście, a ten jak kamień w wodę! Nie bardzo wiedziała, gdzie jeszcze ma zajść, by łaskawie udało jej się odnaleźć łysego mnicha. Z racji, że jej kondycja pozostawiała wiele do życzenia, swój wierny topór ciągnęła za sobą. Żelastwo obijało się o wszystko, co tylko spotkało na swojej drodze. Coś tam słyszała, że niby ważni ludzie mają się hajtać w kaplicy, także pognała tam ile sił miała w krótkich nogach. Nie zwracała uwagi za bardzo na innych człekokształtnych. Kiedy tylko zobaczyła łysą pałę mnicha, nie mogła się powstrzymać.*  Goinnoll! Wszędzie cię szukałam!  *Wrzasnęła jak opętana, zaś sekundę botem spaliła buraka, gdyż dotarło do niej, że mogła przeszkodzić w jakiejś ważnej uroczystości. Spuściła łeb i cichutko podeszła do przyjaciela, tylko po to, by się za nim jakoś schować.*  Nie przerywajcie sobie…  *Mruknęła jeszcze*  
Josabelle:   *Głos Kapłanki rozbrzmiewał donośnie pośród ścian kaplicy*  \\ Miłość cierpliwa jest, łaskawa jest.  Miłość nie zazdrości, nie szuka poklasku,  nie unosi się pychą, nie dopuszcza się bezwstydu, nie szuka swego,  nie unosi się gniewem,  nie pamięta złego, nie cieszy się z niesprawiedliwości,  lecz współweseli się z prawdą.  Wszystko znosi,  wszystkiemu wierzy, we wszystkim pokłada nadzieję,  wszystko przetrzyma.\\  
Goinnoll:   *Łysy mnich walną się otwartą ręką w czoło. No tak, nie ma to jak krasnoludzica wpadająca do kaplicy. Dobrze ze nie miała topora przy sobie, gdyż mogło być to uznane za zamach stanu…*  Bogowie, musisz tak wpadać i drzeć się od progu?  *Spytał szeptem swojej przyjaciółki. Ale, czego mógł się po niej spodziewać?*  
Naneth Ulver:   *Spojrzała na niego  spod oka..*  Doprawdy kochany, zbytek łaski. Mną się nie przejmuj . Wszak ojciec wysłał Lehara.. potowarzyszy mi nim nie wrócisz. mam nadzieje,że nie wcześniej niż za 9 miesiecy.. Obiecuje solennie o narodzinach pierworodnego poinformowac cie niezwłocznie.. *rzuciła szeptem i niby niechcący wbiła mu obcas bucika w pałce prawej stopy..*  łuzej nie mogłeś zaplanować tej uroczystości prawda skarbie. Pociesza mnie fakt, że męczysz się bardziej niz ja.. 
Lher Hanrid:  No przepraszam, nooo…  *Szepnęła mu do ucha, wcześniej stając na palcach, by wykonać to niebywale trudne zadanie. Następnie zamknęła usta na kłódkę, nie chcą ponownie przeszkodzić w tak ważnej uroczystości. Miała nadzieję, że zgromadzeni ludzie jej nie widzą.*  
Josabelle:  http://www.youtube.com/watch?v<br />\n=indlKo9lD1c&feature=player_em 
Josabelle:   *Gdy już czytać skończyła poprosiła młodych o zbliżenie się do ołtarza po czym sama zeszła aby stanąć bliżej nich i szepnęła *  Teraz przejdziemy do przysiegi  *po czym nieco głośniej zapytała*  Czy chcecie dobrowolnie i bez żadnego przymusu zawrzeć związek małżeński? 
Roinaven Ulver:  - Leher? To przypadkiem nie ten twój przyjaciel z dzieciństwa któremu wystawiłem imienny rozkaz wysyłający go w najodleglejszy zakątek Cesarstwa, pod karą śmierci? Bawcie się dobrze niż go zabiorą gwardziści.  * Uśmiechnął się wrednie prostując sylwetkę. Jutro sam będzie musiał stawić się na froncie. A to jego ostatnie chwile w Alearze. Jakże urocza historia. Wojownik wyruszający na wojnę żeni się dzień przed wyruszeniem w podróż. Nie mógł opanować cynicznego uśmiechu. *  - Tak.  * Odparł głośno i bez wahania kapłance. Na pohybel rudej małpie. - dodał w myślach. *   
Goinnoll:   *Mnich pokręcił tylko głowa, i dalej obserwował ceremonie. Słuchał uważnie słów kapłanki. Obserwował namiestnika i jego wybrankę. Namiestnik potwierdził. Jeszcze Hrabina. Różne o niej plotki chodziły po mieście. Tak, więc czekał na dalszy ciąg*  
Naneth Ulver:  Ehh musiała podejść i stanąć z nim twarzą w twarz.. Uniosła głowę lekko, z nieukrywana duma, by pokazać mu,że ma za nic jego słowa i perfidny wyraz twarzy. Gdyby widział jej spojrzenie, wiedział by, jak błyszcza jej oczy na myśl o tym, że zostawi ją w spokoju *- Dostał trzy tygodnie przepustki na nasz slub . Ktoś przypadkiem zadbał by Namiestnik dzielił szczęście ze swymi żołnierzami..Dziękuję za zyczenia .. Nie omieszkam skorzystać z tak cennej rady jak twoja..* rzuciła mu cicho nim padło *- Tak..*  miękki i delikatny  kobiecy głos powiódł sie po pomieszczaniu splatając się z łagodnymi nutami rozbrzmiewającej wokół muzyki. Jak można tak kłamać. Demony kłamstwa śmiały się ubawione nie dając jej o tym zapomnieć.* 
Josabelle:   *Uśmiechnęła się do Roinaven\\  a i Naneth myśląc, że plotki które słyszała ani trochę nie odzwierciedlały prawdy o hrabinie i jej przyszłym mężu, a wręcz przeciwnie oboje wyglądali na szczęśliwych*  Czy chcecie wytrwać w tym związku w zdrowiu i chorobie, w dobrej i złej doli, aż do końca życia? 
Roinaven Ulver:   * Wyszczerzył zęby w parodii uśmiechu, po części też będącej wynikiem słów tej... kobiety która właśnie kopała sobie grób. Bardzo ciemny i głęboki. *  - Tak.  *Oznajmił swoim donośnym głosem. Tak by wszyscy słyszeli. Kątem oka dostrzegł matkę Naneth, szlochającą ze szczęścia. A on przezywał właśnie najgorszy moment w całym swoim życiu. Jawne publiczne upokożenie. *  - ja też .. dotrzymam ci wierności .. najdroższa.  * Szepnął do prawie żony przez zaciśnięte w dziwnym uśmiechu zęby. *   
Naneth Ulver:   *słowa kapłanki były wyjątkowe, jak i cała ceremonia.. Jaka szkoda, ze przed nią stał pętak bez czci i honoru a nie mężczyzna któremu oddała by całą siebie jego stretny wyraz gęby sprawiał jej tylko satysfakcje, która ukazała mu trzepocząc rzęsami jak zakochane do nieprzytomności dziewczę.* - Tak.. *odrzekła mu miękko acz pewnie wiedzac jakie katusze przeżywa, gdyż wyraźnie widziała w jego oczach gniew i wściekłość..* - Alez skarbie .. Cóż za rozkosz słyszec to z twych ust.. Doprawdy nie pozamykali jeszce wszystkich burdeli w mieście? Musiałes przelecieć wszystkie dziewki stąd do Ilm Usul.. czyżby jakas jeszce została. Baw sie w takim razie dobrze.. *rzuciła mu miekkim, zmysłowym szeptem..*    
Josabelle:  http://www.youtube.com/watch?v<br />\n=NguIpRFLM4M 
Josabelle:  Podajcie sobie prawe dłonie i powtarzajcie za mną.  *rzekla kapłanka*  
Idael:  linki spróbuj wszycać bez przerw... 
Josabelle:  ja daje bez przerw ale jakis blad jest :( 
Josabelle:  i jak tragicznie jest? :P 
Roinaven Ulver:   * Wyciągnął dłoń w stronę swojej ..kobiety. Czekał aż ona wykona swoją część... a może się jednak rozmyśli. Nieee... nie uczyni mu tej przyjemności. A on musi dotrzymać danego słowa. Uśmiechał się i czekał aż ta poniżająca scena wreszcie się skończy. *    
Naneth Ulver:   *O zgrozo musiała dotknąć tego obleśnego gada z rozdwojonym językiem, który bogowie sami wiedza w jakie otwory wsadzał do tejhj pory.. Mimo to zmusiła sie by podac mu dłoń i połozyła ja delikatnie na jego dłoni opuszkami palców mimowolnei zataczajac n aniej delikatne kółka, nim sie nei spostrzegła i nie przestała krzywiąc się w duchu z niesmakiem. Co ją podkusiło.. może poczyta to za złośliwość.. Oby..Ciepło jego dłoni wywołało w niej dreszcz nie była tylko pewna , iż jest to dreszcz obrzydzenia czy tylko niesmaku.*  
Khardrag:  szczerze to nie przeczytalem ani jednego posta bo nie mam czasu ale pewnie jest okej skoro jeszcze cie nei wyjebal nikt :D 
Josabelle:   *Zwróciła się w stronę Roinavena i rzekła*  Zaczniemy od Ciebie, powtarzaj za mną dobrze?  *zapytała po czym kontynuowała*  Ja Roinaven biorę Ciebie Naneth za żonę i ślubuję Ci miłość, wierność i uczciwość małżeńską oraz że Cię nie opuszczę aż do śmierci.  
Idael:  to jak chcesz dawać do dawaj mi...ja dam 
Roinaven Ulver:   *Szkoda że w takim ładnym opakowaniu siedzi takie niewdzięczne, niewychowane i złośliwe stworzenie, wielka szkoda. Takie marnotrawstwo. Westchnął niezauważalnie po słowach kapłanki. Trzeba wreszcie skończyć to przedstawienie. *  -  Ja Roinave...n biorę Ciebie Naneth za żonę, i ślubuję Ci miłość, wierność i uczciwość małżeńską oraz że Cię nie opuszczę aż do śmierci.  * Oby rychło nastąpiła. Dokończył już w myślach słowa formułki które z taką powaga właśnie wypowiedział na głos. To przedstawienie było o wiele bardziej męczące niż mógł przepuszczać. Wolał by się znaleźć pomiędzy wilkami z nożem niż tu, przed tą kobietą. Miał by znacznie większe szanse. *  
Josabelle:  Teraz Twoja kolej Nan  *powiedziała Josabelle z lekkim uśmiechem który miał podnieść kobietę na duchu*  Ja Naneth biorę Ciebie Roinaven\\  ie za męża i ślubuję Ci miłość, wierność i uczciwość małżeńską oraz że Cię nie opuszczę aż do śmierci.  
Naneth Ulver:   *Nawet kapłanka musiała zauważyć, że jest niedorozwinięty.. Ale wstyd.. Zwracała się do niego jak do chorego na umyśle pacana. I miała rację, co wywołało na twarzy Hrabiny słodki, ciepły uśmiech , zaś w jej oczach delikatne iskierki rozbawienia. .. Skinęła głowa delikatnie po czym powtórzyła za kapłanką.. *  Ja Naneth biorę Ciebie Roinavenie za męża i ślubuję  miłość, wierność i uczciwość małżeńską oraz, że Ci nie odpuszczę aż do śmierci.* Mojej lub twojej .. mówiły jej myśli..Modulowała głosem by drżał miękko i zmysłowo, jak w ekscytacji wplatając w jego ton nieśmiałość, która miała skryć wstręt i pagodę.. Jednak treści przysięgi nie mogła sobie odpuścić..  
Idael:  ,,Parse error: syntax error, unexpected T_VARIABLE in /home/virt100415/domains/alear<br />\na.pl/public_html/includes/chec<br />\nkexp.php on line 92\\ podrórze nie działają... 
Josabelle:  *Gdy oboje wypowiedzieli słowa przysięgi kapłanka obróciła się w stronę małej pyziatej dziewczynki stojącej za pobliską kolumną i skinęła na nią aby ta podeszła z obrączkami. Następnie gdy ta zrobiła to o co poprosiła ją kapłanka odwróciła się w stronę młodych i z uśmiechem rzekła. Teraz nałożycie sobie obrączki z słowami: \\  Przyjmij tę obrączkę jako znak mojej miłości i wierności.\\    
Roinaven Ulver:   *Swoją drogą, musiał przyznać kapłanka miała stalowe nerwy, jako jedyna słyszała wymianę \\ czułości\\  pomiędzy nim a rudym potworkiem który własnie przekręcił słowa przysięgi. Widać zapamiętanie ich przekraczało możliwości intelektualne jego zony. Trudno. Wziął obrączkę i wcisnął ją na palec Naneth. *  - Przyjmij tę obrączkę jako znak mojej miłości i wierności...  *Wycedził mając ciesząc się już ze zbliżającego końca tej farsy. *   
Naneth Ulver:   *Ujęła w dłoń symbol , który miał przypieczętować jej los.. Ot delikatna, pięknie ażurowana , złota obrączka .. Piękny przedmiot a tak znienawidzony.. Na moment zapatrzyła się weń a jej oczy rozszerzyły się nieznacznie.. Nałożyła ją na palec tej pokraki udającej prawdziwego mężczyznę..* Przyjmij tę obrączkę jako znak  miłości i wierności. *wyszeptała lekko zdając sobie dokładnie sprawę z tego, ze ni eskłamie i demonów nie podsyci w końcu szanowny pan namiestnik jedyna miłość jaka wyznawał była miłośc własna, no chyba, ze bunga bunga w wykonaniu szympansa tez tak nazywał.. Na szczęście jej tego oszczędzi przynajmniej na razie.*  
Josabelle:  http://www.youtube.com/watch?v<br />\n=Uq5cpGZV76A 
Josabelle:  Na mocy praw nadanych mi przez bóstwa i władze ogłaszam Was mężem i żoną możecie się pocałować albo i nie .... *dodała juz szeptem kapłanka widząc umęczoną minę namiestnika i hrabiny*  
Roinaven Ulver:   *Tego nie mógł sobie odpuścić, jakkolwiek nie trawił tej kobiety, przyjemnym mu było odpłacaniem pięknym za nadobne. Widział doskonale jak się go brzydziła. Jak wstrętny jej był. Miał jedynie nadzieję że nie zarzyga mu ubrania. Poderwał jej welon i nachylając się wpił w jej usta w gorącym, długim i obleśnie namiętnym pocałunku odbierających oddech. Masz i cierp. Krowo. *   
Idael:  http://www.youtube.com/watch?v<br />\n=Uq5cpGZV76A 
Idael:  rzeczywiście błąd... 
Josabelle:  no ale nic :) jakps dotrwalismy do konca :P chodz Pani młoda uciekla :) 
Idael:  zarzygała się na śmierć :D 
Roinaven Ulver:  // Nance chyba zdechł komp, albo siadło łącze, jak się nie zjawi w 5 minut, znaczy uroczystość zakończyła się bez wiekszych ekscesów i zamieszek.  
Idael:  // Why? Ludzie tu przyszli się ponabijać...bot nie może za nią chwilę pograć? 
Josabelle:   *Kapłanka odmówiła jeszcze krótką modlitwę nad małżonkami po czym rzekła*  Życzę szczęścia na nowej drodze życia  *po czym w myślach dodała i \\ nie pozabijajcie się. Następnie pożegnała młodych i udała się do swojej komnaty\\ *  
Roinaven Ulver:   * No to przyszedł czas opuszczenie świątyni. Idąc powoli, pod ręce, uśmiechali się oboje. Potem były gratulacje zaproszonej garstki, a po wszystkim oboje wsiedli do żałobnego powozu nowożeńców i odjechali do rezydencji Namiestnika. Nie żyli długo i szczęśliwie . Bad End. *  
Josabelle:  wybacz, że tak sie przeciagnelo :) 
Roinaven Ulver:  było ok, swietna ceremonia  
Josabelle:  dziekuje :) chodz wedlug mnie nie wszystko wyszlo bo boty przestaly mi dzialac i musialam pisac we wlasnym imieniu :P 
Naneth Ulver:   *jego oblesny jęzor dostał sie w jje usta ale nie na długio bo ugryzła go siarczyście zaciskajac zeby. masz perfidny śmierdzielu.. ot i koniec cyrku. Kidy sie od niej odkleił usmiechneła sie ciepło i ruszyła do wyjścia u jego boku wbijajac mu pazury w reke.*  Jeśli zrobis zto jeszce raz obudzisz sie bez ptakszka.. *warkneła do niego kiedy opuszczali świątynię.*  
Roinaven Ulver:  było dobrze, na przyszłość masz juz gotowy ceremoniał  
Roinaven Ulver:   *w karecie całował ją jeszcze wiele razy. *   
Naneth Ulver:   *nie ma to jak mokre sny namiestnika o karecie i vcałowaniu starej krowy*  
Roinaven Ulver:  * a potem poszedł do siebie a ją zostawił z gwardzistami szukającymi jakiegoś goscia któremu anulowano przepustkę i natychmiast ma wracać na pustynie walczyć ze smileodonami. *   
