<?php /* Smarty version 2.6.16, created on 2012-10-06 07:44:58
         compiled from poradnik.tpl */ ?>
<center>
<br><b>Jak grać? - Krótki poradnik!</b><br></center>

<p>Jeśli nigdy wcześniej nie miałeś nic wspólnego z grami tego typu - Przeczytaj ten poradnik! Te kilka zdań rozjaśni Ci grę!<br>
</p><p>Aleara to gra oparta na symulacji średniowiecznego cesarstwa. Gracz wciela się w jedną z ras, klas i podklas mechanicznych gry. Gra polega na rozwijaniu swej postaci, wbijaniu poziomów, oraz oferuje dużo więcej możliwości. W grze można zajmować się swoją farmą, strażnicą, tworzyć przedmioty, walczyć z innymi graczami i potworami, handlować i wiele, wiele innych możliwości. Gra bazuje na systemie energii gracza. To ile zrobimy w grze w ciągu godziny zależy właśnie od niej. W górnym panelu gry widzimy wskaźnik energii. Załóżmy mamy Energia: 150/500 (+8.00). Oznacza to, iż mamy 150 energii, 500 limitu energii, +8.00 nowej energii którą dostajemy trzy minuty po każdej równej godzinie. Większość rzeczy które chcemy zrobić w grze pobiera nam energię, lecz przed pobraniem jej jesteśmy o tym informowani (nie każdy ruch w grze pobiera energię, tylko czynności wykonywane). Liczba przy nicku gracza oznacza jego numer identyfikacyjny. Główną lokacją, gdzie możemy zdobywać doświadczenie, co za tym idzie - poziomy, to arena walk, lecz aby zacząć walczyć trzeba kupić sobie ekwipunek w mieście do którego wchodzimy przez menu lewe w grze. Mamy do wyboru kilkanaście ras, klas i podklas postaci. Klasa rzemieślnik opiera się głównie na tworzeniu przedmiotów (jest to dość skomplikowane), klasa mag włada magią, a pozostałe klasy to klasy walczące głównie wręcz i dystansem. W grze wyróżniamy podstawowe statystyki takie jak: <br>
</p><br>
<b>siła</b> - u postaci walczącej wręcz odpowiada za obrażenia.<br>
<b>zręczność</b> - u postaci walczącej wręcz odpowiada za trafianie, u dystansowej - trafianie oraz obrażenia.<br>
<b>szybkość</b> - odpowiada za szybkość zadawania ataków.<br>
<b>wytrzymałość</b> - odpowiada za zmęczenie postaci, punkty życia oraz za obronę.<br>
<b>inteligencja</b> - u maga odpowiada za obrażenia. (główna cecha maga.)<br>
<b>siła woli</b> - u maga odpowiada za obronę.<br><br>
<br>



<b>Opiszę Wam przykładowe pierwsze kroki w grze według administratora </b><br><br>
(1. Początek) Dowiedziałam się o grze więc wchodzę na www.aleara.pl.  Poleć znajomym  Po szybkiej rejestracji widzę wybór szablonów wewnętrznych gry. Wybieram przykładowo Dark Side. Strona przenosi mnie do kreatora postaci. Czytam zamieszczony tam krótki poradnik. Gdy już znam podstawy o grze klikam 'Rozpocznij tworzenie swojej postaci'. <br><br>
(2. Tworzenie postaci) Kreator postaci prosi mnie o wybór płci. Wybieram Mężczyznę. Później system nakazuje mi wybrać rasę postaci. Przeglądam wszystkie rasy, czytam na szybko opisy ras. Zwracam szczególną uwagę na statystyki otrzymywane za punkty AP które zdobywamy za wbijanie poziomów. Jako iż chcę grać dystansowcem to upatrzyłem sobie Demona. Ma świetny bonus do zręczności za AP. Następnie kreator prosi mnie o wybór klasy. Czytam wszystkie opisy, najbardziej spodobał mi się Łowca, więc go wybieram. Kreator tym razem prosi mnie o wybranie wyznania. Przeglądam wszystkie i zwracam szczególną uwagę na bonusy. Lathander ma bonusy do ważnych cech dla mnie dlatego go wybieram. Później miejsce zamieszkania które jest tylko formalnością. Oczywiście w grze jest więcej miast, lecz Aleara jest miastem domyślnym. Moja postać jest już wykreowana. <br><br>
(3. Obserwacje w grze) Po przejściu przez kreator postaci gra przenosi mnie do miasta Aleara. Zaczynam się rozglądać po szablonie gry. Dostrzegam listę graczy online po prawej stronie oraz numery obok Nicków -są to numery identyfikacyjne graczy (ID). W górnym panelu gry pod logo widzę zaś wskaźniki graficzne i tekstowe poziomu życia, many, energii oraz doświadczenia. Następnie przeglądam po kolei menu po lewej - nawigację. <br><br>
(4. Przygotowanie do gry) Znajduję w menu nawigacji ‘Czat’. Mogę wejść na niego i przywitać się kulturalnie z innymi graczami. W innej zakładce otwieram sobie ‘Opcje konta’ z menu nawigacji. Wgrywam sobie avatar, ustawiam opis oraz w opcjach dodatkowych włączam edytor, raportowanie walk na pocztę oraz wyłączam panele (ponieważ mi akurat przeszkadzały). <br><br>
(5. Pierwsze ruchy mechaniczne) Na początku muszę rozdać swoje punkty AP które otrzymałem na start, więc wchodzę do statystyk, następnie w punkty AP. Po krótkim zastanowieniu postanowiłem, że rozdam AP następująco: 8 pkt w zręczność, 4 pkt w wytrzymałość, 3 pkt w szybkość. Gdy mam już rozdane punkty AP, nadszedł czas abym założył ekwipunek. Jako, iż mam na razie niezbyt wiele wytrzymałości, nie będę szaleć z ekwipunkiem ponieważ postać będzie się męczyć. Udaję się najpierw do fleczera w mieście Aleara aby zakupić łuk i strzały. Pojawia mi komunikat, iż nie mam tyle pieniędzy. Wchodzę od depozytu w menu nawigacji i wypłacam połowę złota które otrzymałem na start. Wracam do fleczera i zakupuję sprzęt. Następnie wchodzę do ekwipunku i zakładam łuk, a następnie strzały. Gdy mam już postać przygotowaną do gry mogę wybrać sobie prezent. Wchodzę w ‘Odbierz prezent’ które znajdę w menu nawigacji na samej górze. Wybrałem sobie Jednorożca Czarnego Pana, a za resztę z 1000pkt -  złoto. <br><br>
(6. Pierwsze zdobyte doświadczenie) Mam postać przygotowaną do walki, dlatego czas udać się na Arenę Walk. Wybieram trening z potworami oraz najsłabszego potwora z listy. Ustawiam walkę. Wyświetla mi się przebieg z walki, udało mi się zabić potwora. Wracam i ustawiam walkę z dwoma potworami jednocześnie jeden raz. Znów wygrałem. Zauważam, iż tak idzie szybciej i tym oto sposobem udało mi się wbić poziom. W międzyczasie co kilka walk uzupełniałem kołczan strzałami i naprawiałem broń w ekwipunku (wraz z walką coraz bardziej niszczeje). System poinformował mnie o zdobytych punktach AP, dlatego też udaję się do statystyk i rozdaję AP. 6pkt w zręczność, 3 pkt w wytrzymałość, 1 pkt w szybkość. Wracam na arenę i walczę już z coraz to lepszym potworem. Udało się go zabić kilka razy i wbić kolejny poziom. Znów rozdałem podobnie punkty. <br><br>
(7. Inwestycje i odnawianie energii) Rozglądając się po mieście zauważyłem strażnicę. Zakupiłem ją. Będzie moim głównym źródłem zarabiania złota poprzez ściąganie danin. Powoli będę sobie ją rozkręcał. Zauważyłem też w mieście Plugawy Ogród. Udałem się do Lasu Zbłąkanych Dusz przez menu nawigacji podróżując na moim koniu, a przeszukując las znalazłem m. in. sadzonki. Wróciłem do Aleary i zasadziłem sadzonki w Plugawym Ogrodzie. Za 5 dni będę mógł ściąć drzewa. Co reset (godzinę) także odpoczywam sobie na moim Jednorożcu Czarnego Pana w zagrodzie dla koni. Odnawia on mi sporo energii. W menu nawigacji dostrzegłem też link 'Głosuj na nas'. Po oddaniu kilku głosów otrzymałem denary za które w późniejszym czasie mogę kupić sobie nawet rangę rycerza (wystarczy, że będę codziennie oddawać głosy tam na Alearę). Następnie pojechałem na Krwawe Mokradła i błąkając się w Puszczy Krutynów dotarłem do Starej Sali. Odbieram tam bonus i zauważam, iż mogę go odbierać dwa razy w ciągu godziny. Dostaję za to dodatkową energię, jak i złoto oraz doświadczenie. <br><br>
(8. Gra do 10 lvlu) Później gdy miałem już więcej energii udałem się do Areny Walk i zdobyłem kolejne poziomy walcząc z coraz mocniejszymi potworami. W międzyczasie zajmowałem się plugawym ogrodem, farmą, strażnicą i innymi ciekawymi patentami. Moja postać stawała się coraz mocniejsza i zajmowała coraz to lepsze miejsce w rankingu. Znalazłem sobie nawet gildię w której miałem świątynię, która dawała mi buffy zwiększające statystyki. Wspólnie z innymi graczami zdobywałem prestiż dla gildii i kolejne poziomy. <br><br>
(9. Gdy osiągamy 10 lvl) Gdy osiągnąłem już 10 poziom mojej postaci stoją przede mną otworem nowe możliwości. Wybrałem sobie podklasę w statystykach, zakupiłem pierścienie od rzemieślników oraz zacząłem korzystać z nowych lokacji w puszczy krutynów.<br><br>
(10. Gdy osiągniemy 25 lvl) Gdy udało mi się zdobyć 25lvl zakupiłem od innych graczy jednorazowe kluczyki do miasta Diabolium (które ja mógłbym dopiero kupić od 30 lvlu). Zacząłem podróżować po cmentarzysku i zdobywać artefakty potrzebne do wywołania bossa Diaburiona. Udało mi się z niego nawet zdobyć magiczny przedmiot (rar). Biłem go codziennie maksymalną ilość razy (6). Dawał mi on znaczną ilość doświadczenia oraz złota. <br><br>
(11. Gra 25+ lvl) Gdy miałem już poziom zbliżony do 30 i posiadałem sporo mithrilu, sosny oraz złota z Cmentarzyska Diaburiona w Diabolium, szamani robili mi wywary transmutacji. Pijąc dziennie jeden dodawało mi to sporo doświadczenia oraz dawało nowe możliwości. Moja postać stawała się coraz mocniejsza. Zdobywałem coraz mocniejsze przedmioty, ulepszałem je w opuszczonej kuźni, magowie mi je umagiczniali, a ja piąłem się w rankingu ku górze… <br><br>