<?php /* Smarty version 2.6.16, created on 2013-02-14 14:30:04
         compiled from travel.tpl */ ?>
<?php echo '<center><IMG SRC="images/locations/bramymiasta.png"></center><img style="margin-left: -8px" width="538px"  src="liniuszka.png"><br><br>Poczułeś nagły napływ sił i niezmierną chęć wyruszenia poza miasto. Przygotowujesz się do wyprawy, zabierając niezbędne rekwizyty mogące przydać się podczas długiej drogi. Gdy spakowałeś już prowiant oraz uzbrojenie na wypadek ataku bandytów powoli kierujesz się ze swojego domku ku bramom miasta Aleary. Wszystko wygląda jak co dzień. Przechodząc obok targowiska widzisz stale kłócące się o cenę przekupki, grajka na murku tuż przy fontannie, obejmujący się zakochanych na pobliskich ławkach... Nagle znienacka widzisz przed sobą jadącego konno samego króla. Składasz mu pokłon i udajesz się do bram miasta. Strażnicy, których mijasz uważnie przypatrują się Twojej osobie pełniąc służbę i strzegąc miasta. Gdy uznali, że możesz je opuścić krainę przechodzisz przez bramę...<br>';  if ($this->_tpl_vars['Action'] == '' && $this->_tpl_vars['Action2'] == ''):  echo '';  echo '';  if ($this->_tpl_vars['Location'] == $this->_tpl_vars['LCapitol'] || $this->_tpl_vars['Location'] == $this->_tpl_vars['LElvenCity']):  echo '<p>';  echo $this->_tpl_vars['Stablesinfo'];  echo '</p>';  else:  echo '<p>';  echo $this->_tpl_vars['Outside'];  echo '</p>';  endif;  echo '';  echo '';  if ($this->_tpl_vars['Location'] == $this->_tpl_vars['LCapitol']):  echo '<table><tr><td><fieldset style="width:90%"><legend><b>Standardowe przejazdy:</b></legend><a href="travel.php?action=gory">';  echo $this->_tpl_vars['Amountains'];  echo '</a><br><a href="dojazddiabolium.php?akacja=zm">Diabolium [wymagany klucz do miasta]</a><br><a href="port.php?akcja=zm">Wyspa Złota (Przejazd 100000 złota)</a><br><a href="port.php?akcja=mz">Wyspa Mithrilu (Przejazd 50000 złota)</a><br><a href="travel.php?action=las">';  echo $this->_tpl_vars['Aforest'];  echo '</a>  <br><a href="travel.php?action=city2">';  echo $this->_tpl_vars['Aelfcity'];  echo '</a> <br></fieldset"><br><br></td><td>';  if ($this->_tpl_vars['Houseid'] > '0'):  echo '<fieldset style="width:100%"><legend><b>Darmowe Przejazdy na koniu:</b></legend><a href="stajnia1.php?akcja=altara">Aleara</a><br><a href="stajnia1.php?akcja=felwood">Krwawe Mokradła</a><br><a href="stajnia1.php?akcja=gory">Góry Przeznaczenia</a><br><a href="stajnia1.php?akcja=las">Las Zbłąkanych Dusz</a><br><br><Br><br><br></fieldset> ';  endif;  echo '<td></tr></table><br><Br>';  if ($this->_tpl_vars['Maps'] == 1):  echo '<p>';  echo $this->_tpl_vars['Portal1'];  echo '</p><ul><a href="travel.php?akcja=tak">';  echo $this->_tpl_vars['Ayes'];  echo '</a><a href="travel.php?akcja=nie">';  echo $this->_tpl_vars['Ano'];  echo '</a></ul>';  endif;  echo '';  if ($this->_tpl_vars['Tportals'][0] != ''):  echo '<p>';  echo $this->_tpl_vars['Tporinfo'];  echo '</p><ul>';  unset($this->_sections['portals']);
$this->_sections['portals']['name'] = 'portals';
$this->_sections['portals']['loop'] = is_array($_loop=$this->_tpl_vars['Tportals']) ? count($_loop) : max(0, (int)$_loop); unset($_loop);
$this->_sections['portals']['show'] = true;
$this->_sections['portals']['max'] = $this->_sections['portals']['loop'];
$this->_sections['portals']['step'] = 1;
$this->_sections['portals']['start'] = $this->_sections['portals']['step'] > 0 ? 0 : $this->_sections['portals']['loop']-1;
if ($this->_sections['portals']['show']) {
    $this->_sections['portals']['total'] = $this->_sections['portals']['loop'];
    if ($this->_sections['portals']['total'] == 0)
        $this->_sections['portals']['show'] = false;
} else
    $this->_sections['portals']['total'] = 0;
if ($this->_sections['portals']['show']):

            for ($this->_sections['portals']['index'] = $this->_sections['portals']['start'], $this->_sections['portals']['iteration'] = 1;
                 $this->_sections['portals']['iteration'] <= $this->_sections['portals']['total'];
                 $this->_sections['portals']['index'] += $this->_sections['portals']['step'], $this->_sections['portals']['iteration']++):
$this->_sections['portals']['rownum'] = $this->_sections['portals']['iteration'];
$this->_sections['portals']['index_prev'] = $this->_sections['portals']['index'] - $this->_sections['portals']['step'];
$this->_sections['portals']['index_next'] = $this->_sections['portals']['index'] + $this->_sections['portals']['step'];
$this->_sections['portals']['first']      = ($this->_sections['portals']['iteration'] == 1);
$this->_sections['portals']['last']       = ($this->_sections['portals']['iteration'] == $this->_sections['portals']['total']);
 echo '<a href="portals.php?step=';  echo $this->_tpl_vars['Tporlink'][$this->_sections['portals']['index']];  echo '">';  echo $this->_tpl_vars['Tportals'][$this->_sections['portals']['index']];  echo '</a>';  endfor; endif;  echo '</ul>';  endif;  echo '';  else:  echo '';  echo '<ul>';  if ($this->_tpl_vars['Location'] == $this->_tpl_vars['LMountains'] || $this->_tpl_vars['Location'] == $this->_tpl_vars['LElvenCity']):  echo '<table><tr><td><fieldset style="width:90%"><legend><b>Standardowe przejazdy:</b></legend><a href="travel.php?action=gory">';  echo $this->_tpl_vars['Amountains'];  echo '</a><br><a href="dojazddiabolium.php?akacja=zm">Diabolium [wymagany klucz do miasta]</a><br><a href="port.php?akcja=zm">Wyspa Złota (Przejazd 100000 złota)</a><br><a href="port.php?akcja=mz">Wyspa Mithrilu (Przejazd 50000 złota)</a><br><a href="travel.php?action=las">';  echo $this->_tpl_vars['Aforest'];  echo '</a><br><a href="travel.php?action=city2">';  echo $this->_tpl_vars['Aelfcity'];  echo '</a><br>';  else:  echo '<br>';  endif;  echo '<a href="travel.php?action=powrot">';  echo $this->_tpl_vars['ACapitol'];  echo '</a></ul></fieldset"><br><br></td><td>';  if ($this->_tpl_vars['Houseid'] > '0'):  echo '<fieldset style="width:100%"><legend><b>Darmowe Przejazdy na koniu:</b></legend><a href="stajnia1.php?akcja=altara">Aleara</a><br><a href="stajnia1.php?akcja=felwood">Krwawe Mokradła</a><br><a href="stajnia1.php?akcja=gory">Góry Przeznaczenia</a><br><a href="stajnia1.php?akcja=las">Las Zbłąkanych Dusz</a><br><Br><br><br></fieldset> ';  endif;  echo '<td></tr></table><br><Br>';  endif;  echo '';  endif;  echo '';  if ($this->_tpl_vars['Action2'] != ''):  echo '<ul><li><a href="travel.php?akcja=';  echo $this->_tpl_vars['Action2'];  echo '&amp;step=caravan">';  echo $this->_tpl_vars['Acaravan'];  echo '</a> </li><li><a href="travel.php?akcja=';  echo $this->_tpl_vars['Action2'];  echo '&amp;step=walk">';  echo $this->_tpl_vars['Awalk'];  echo '</a> </li><li><a href="travel.php?akcja=';  echo $this->_tpl_vars['Action2'];  echo '&amp;step=teleport">';  echo $this->_tpl_vars['Ateleport'];  echo '</a> </li><li><a href="stajnia.php">Podróż koniem</a> </li><li><a href="travel.php">';  echo $this->_tpl_vars['Aback'];  echo '</a> </li></ul>';  else:  echo '';  if ($this->_tpl_vars['Portal'] == 'Y'):  echo '';  echo $this->_tpl_vars['Portal2'];  echo '';  elseif ($this->_tpl_vars['Portal'] == 'N'):  echo '';  echo $this->_tpl_vars['Portal3'];  echo '';  endif;  echo '';  endif;  echo ''; ?>
</br></br>