<center><b>Opis karczmy:</b></center>
<img style="margin-left: -8px" width="538px"  src="liniuszka.png"><br>
<p>Gdzież lepiej założyć karczmę, niż w Alearze, stolicy wszystkich poszukiwaczy przygód? Może niezbyt sprzyjające warunki, las zbłąkanych dusz nie ma zbyt dobrej renomy, do tego piekielny mróz ciągnie od tej drzewnej ostoi. Sama karczma nie jest zbyt łatwa do odnalezienia, nie ma też jako takiej nazwy, "Nazwa już wkrótce - pertraktujemy" jeno taki napis widnieje na naprędce wymalowanej tabliczce z drewna, które napewno widywało lepsze dni . "Ty który tu wchodzisz porzuć wszelką.... Witamy?" ów szyld nad drzwiami, to pierwsze co Ci się rzuca w oczy, gdy wchodzisz do karczmy pośród gąszczu budynków Aleary. Szybko jednak zauważasz więcej szczegółów. Pomieszczenie jest obszerne i niezwykle ciemne - tych kilka przydymionych okien nie przepuszcza wiele światła. Tu i ówdzie porozstawione są stoły w kształcie pajęczyny, widać karczmarz gustuje w owych wzorach. Stoły prezentują się trochę niesamowicie, nici pajęczyn na nich świecą widmowym światłem, pewnie za sprawą magii. I tak oto nawet w przyjemnym półmroku można było bez szwanku przedostać się do baru, z ustawionymi przy nim krzesłami. Jak forteca broniąca beczek, i butelek z trunkami, które zdobią ścianę naprzeciw wejścia, jak drogocenne klejnoty. A żeby się do nich dostać, wystarczyło lawirować między stolikami. Wyjątkiem jest stół biesiadny - przygotowany przezornie na większe towarzystwo, co to razem biesiadować będzie. Ten znajdował się nieopodal baru, nieco na prawo od wejścia, jakby kolos chciał schować się przed wzrokiem nowoprzybyłych. 
Z sufitu zwisa bodaj jedyne źródło światła - żyrandol ze skamieniałych, spętanych ze sobą macek, z których każda trzyma świecę. Gdy odwracasz wzrok możnaby się przysiąc, że któraś z nich się właśnie poruszyła. Na prawo znajdują się pokoje gościnne, w ilości dwóch, przynajmniej tak mówiono. Górne piętro było podobno kwaterami Karczmarza i właściciela karczmy, ale było tyle strasznych historii o nich, że nikt nie odważył się tam zaglądać. Ale w tym samym momencie Twój wzrok przykuwa inny widok - otóż za topornie ciosaną ladą z drzewa hebanu stoi średniego wzrostu człowiek o czarnych włosach, umięśnionym ciele, opętańczym wzroku i jeszcze bardziej opętanym uśmieszku. Może i trochę podejrzane, ale to nic dziwnego - gdyby nie fakt, że mocno podejrzaną chochlą miesza w imponujących rozmiarów kotle…　Nie ma wątpliwości, że z produkowanej przez mieszańca mazi na chwilę wypłynęła sparaliżowana strachem twarz elfa. Nagle trudno pozbyć się myśli co też dzieje się w piwnicy tego przybytku, lecz kto odważy się wejść przez drzwi, na lewo od baru i zejść, sprawdzić?… 
</p><p>W tym samym momencie Cię dostrzega. Opierając się o jedną z dwóch ogromnych beczek piwa przemawia. 
</p><p>-Witam, jestem Hank, co do picia? A może masz ochotę coś … przekąsić?- po czym człowiek wybucha przerażającym śmiechem.
</p><img style="margin-left: -8px" width="538px"  src="liniuszka.png"><br>
<center><b>Mapa karczmy:</b></center>
<img style="margin-left: -8px" width="538px"  src="liniuszka.png"><br>
<center><IMG SRC="k2.png" style="margin-left: -8px" width="538px"></center>
<img style="margin-left: -8px" width="538px"  src="liniuszka.png"><br>
<center><b>Meni:</b></center>
<img style="margin-left: -8px" width="538px"  src="liniuszka.png"><br>
<center><IMG SRC="http://i.imagebanana.com/img/zm2bxi2b/menu.jpg"></center>