
<img style="margin-left: -8px" src="ramy/magia.jpg">
<p>Magia jest niczym innym jak wykorzystaniem wewnętrznej siły, energii przepływającej przez nasze ciało do tworzenia, czy kreowania zaklęć, materializowania myśli i tym podobne.
</p><p>Każdy człowiek posiada w sobie naturalną więź z tą energią, lecz nie każdy nawet mimo wieloletniego szkolenia potrafi sprostać jej okiełznaniu.
</p><p>Gdy już się to komuś uda, może siebie nazywać magiem, czarodziejem, lub kimś właśnie tego pokroju. Sama zdolność wykorzystywania magii, nie czyni z maga nikogo wyjątkowego.
</p><p>Każda osoba posiada pojemność magiczną, czyli naturalne ograniczenie przepływu magii przez swoje ciało. Magowie potrafią ściągać energię magiczną, która jest wszechobecna, przepuszczać przez własne ciała i myślami, gestem formować zaklęcia. Niektórzy musze najpierw zmagazynować moc w sobie, by potem ją uwolnić, niektórzy działają jak swoisty katalizator, lecz tych drugi jest zaledwie garstka.
</p><p>Załóżmy, że mag potrafi zgromadzić w sobie tylko tyle mocy by uwolnić płomienną kulę, to po jej wykreowaniu przez pewien czas nie ma mowy by mógł to znowu zrobić. Stąd też każdy mag ćwiczy nie tylko siłę woli, czy nie tylko zgłębia nową wiedzę, ale także winien poprawiać i powiększać swoje możliwości akumulacyjne.
</p><p>Absorbowanie magii to jednak nie wszystko, musimy zwrócić uwagę na fakt, z jaką kreacją współgra nasze ciało. Jeżeli wykazujemy ogromną więź z naturą, to przenigdy mag nie będzie w stanie stworzyć zaklęcia pochłaniającego życie i odwrotnie. Raz określona ścieżka skutkuje dożywotnią wiernością.
</p><p>Zbytnie nadwyrężenie organizmu przy tworzeniu zaklęć w pierwszych odczucia skutkuje mocnym uczuciem zmęczenia, osłabienia, ale w efekcie prowadzi do skrajnego wyczerpania organizmu i śmierci.
</p><p>Szkół magii jest wiele, ale nie są one jednak ograniczone w swojej ilości.
</p><p>Zatem w naszym świecie rodzaje magii jakie dotąd udało się sklasyfikować to:
</p><br><br>- <b>Magia Krwi</b> – pozwalająca na manipulowanie krwią, często też nazywana jest magią transmutacji, gdyż potężniejsi magowie potrafią tak zmodyfikować swój kod genetyczny i strukturę ciała, że mogą uzbrajać swoje ciało w dodatkowe rzeczy, takie jak skrzela, skrzydła, wzmacniać nogi. Istnieje jednak duże ograniczenie. Musi zostać zachowana masa, czyli wzmacniając mięśnie nóg osłabia się inne, obdarzając się skrzydłami skazujemy się z drugiej strony na pozbawienie innych rzeczy. Jest to niezwykle potężna jak i skrajnie niebezpieczna magia, dla przeciwników jak i dla samego maga.
<br><br>- <b>Magia Tworzenia</b> – wykorzystując elementy czterech żywiołów (ziemi, wiatru, wody, ognia) mag kreuje magiczną energię i przekształca ją w jeden z wyżej wymienionych żywiołów, by potem nadać mu kształt, lub formę zaklęcia. Tacy magowie potrafią manipulować ziemią, wodą, wiatrem czy ogniem, lecz by nadać im potężniejsza formę, muszą posiadać swoiste źródło owego elementu. Czyli Mag wody nie będzie w stanie ugasić pożaru , gdy w pobliżu nie znajdzie żadnego stawu czy jeziora. Ci którzy przekraczają granicę i próbują stworzyć podległy im żywioł kończą raczej dość przykro, stają sami w płomieniach, lub ich płuca zalewa woda, czasem rozsypują się niczym wysuszona ziemia, lub po prostu ulatują jak wiatr.
<br><br>- <b>Magia Umysłu</b> – każdy mag umysłu poszczycić może się znajomością złożonej psychiki istot humanoidalnych. Osoby zajmujące się tym odłamem magii potrafią wpływać na wolę innych, narzucając im swoje zdanie, zmuszać ich do różnych rzeczy. Jest to magia określana mianem „niewidocznej”, gdyż nie ma swojego fizycznego nośnika w postaci zaklęć, a całość opiera się tylko i wyłącznie na woli maga. Potężniejsi magowie mogą także oddzielić swój umysł od ciała, potrafią przenieść go i umiejscowić w żywej istocie przejmując nad nią kontrolę. Wykształcili też swoisty obraz mentalny służący im do porozumiewania się z innymi na dalekie odległości za pomocą myśli.
<br><br>- <b>Magia Przejęcia</b> – jest to rodzaj magii, różniącej się trochę od magii umysłu. Mianowicie jeżeli magia umysłu zakłada przeniesienie umysłu maga w ciało ofiary, tak w tym przypadku jest na odwrót. Magia przejęcia pozwala na przeniesienie duszy, umysłu ofiary w ciało rzucającego zaklęcie, z zachowaniem woli maga, czyli prosto rzecz ujmując na kradzież wspomnień, umiejętności czy innych podobnych rzeczy ofiary i wykorzystanie ich w takim stopniu wyszkolenia jaki reprezentowała ofiara. Przejmując zdolności szermierskie wyszkolonego rycerza mag potrafić będzie z taka samą precyzją posługiwać się mieczem jak on, kradnąc magię innych osób, mag może wykorzystywać zaklęcia innych szkół. Jeżeli czarodziej jest potężny, możliwym jest przejęcia nawet duszy bóstwa, czy demona, dając mu wiele aspektów z tego płynących. Magia ta ma swoje ograniczenia w postaci pojemności magicznej samego rzucającego czar. Gdy mag posiada wytrenowaną zdolność kumulowania energii w swoim ciele, będzie w stanie przejąć więcej umiejętności swojej ofiary, lecz gdy ofiara jest na znacznie wyższym stopniu aniżeli sam czarodziej, wtedy też może on przejąć jedynie cześć zdolności ofiary, lub też będą to zdolności skopiowane, dalekie od oryginału. Zatem by przejąć demoniczną moc, mag musi posiadać pojemność magiczną równą, lub większą mocy demona. Pojemność magiczna nie jest utożsamiana z mocą magiczną, lecz jest ona miarą energii jaką jest w stanie wchłonąć czarodziej. Ilość przejętych osobliwości także zależy od owej pojemności. Raz nabyta dusza pozostaje w okowach, które stworzył czarodziej i na stałe przypisana do maga.
<br><br>- <b>Magia Oręża</b> – magowie oręża potrafią zaklinać swoją wolę w broni lub zbroi, by ta po założeniu dała się prowadzić za pomocą myśli. Czarodziej nie musi być wcale wprawnym szermierzem, by korzystać z szabli, czy miecza. Czarodzieje potrafią także tak szybko przyzywać różnego rodzaju bronie, czy tarcze, że mówi się, iż są ona zaklęte w jakimś innym wymiarze i wezwane, natychmiast ujawniają się w dłoniach maga. Sama broń jest zwyczajna, dlatego wielu magów oręża to kolekcjonerzy magicznych oręży, czy zbroi. Wielu z nim zaklina broń po to tylko by była ona lepsza w walce.
<br><br>- <b>Magia Natury</b>, potocznie zwana szamanizmem – tutaj magowie wykorzystują żywe istoty, lecz te o niższej inteligencji. Posiadają władzę nad roślinnością wszelaką i zwierzętami. Te zaś wypełniają polecenia szamana. Jest to pewnego rodzaju odłam magii umysłu, lecz ściśle sprecyzowany w danym kierunku. By przejąć kontrolę nad groźnym zwierzem, czy też nad egzotyczną rośliną mag musi wykazać się większa odeń siłą woli. Mankament jest taki, iż szaman nie może sam niczego tworzyć. Mianowicie, przyzywając pędy jakiejś rośliny liczyć się musi z tym, iż ta mu nie odpowie na wezwanie, musi być ona w pobliżu, lub ten musi posiadać nasiona, z których będzie mogła ona wykiełkować.
<br><br>Zwierzęta, przyzywane reagują tak samo jak roślinność. Szaman musi znajdować się w pobliżu, wilka, jakiegoś ptaka, by ten mu usłużył swoja pomocą. Kontrola nie jest stała i wymaga nieustannego przepływu energii. Mag tworzący zaklęcie rozkazu z chwilą zaprzestania rzucania zaklęcia traci kontrolę nad roślinnością, czy zwierzyną wcześniej przejętą. Wtedy też staje się ona dla niego również niebezpieczna co dla przeciwnika.
<br><br>- <b>Magia Czasu</b> – swojemu użytkownikowi daje władzę nad czasem, lecz w stopniu ograniczonym. Mag może jedynie manipulować czasem na małych obszarach jak również tylko i wyłącznie na przedmiotach nieożywionych z tym wyjątkiem, iż wliczana jest do tego roślinność. Czarodziej może cofnąć czas danego przedmiotu, lub też przyspieszyć go do takiego stopnia, iż uwydatni jego rozkład. Może też za pomocą swojej magii uwidocznić przeznaczenie niektórych przedmiotów. Manipulując czas, wpływa na przestrzeń wokół przedmiotu, że te staje się tym samym przedmiotem, którym miał być np. za 100 lat, lub też czym był 100 lat wcześniej.
<br><br>- <b>Magia Przywołań</b> – daje swojemu użytkownikowi moc kreacji myśli. Mag może stworzyć co tylko zamarzy , począwszy od złota, po legion wojsk. Nie jest to jednak prosta magia, zaklęcia są na tyle złożone, że jeden niewłaściwy ruch czarodzieja rozwiewa przyzwane istoty, czy rzeczy. Magia ta nie jest stała, działa jedynie przez krótką chwilę, dlatego też nie jest w stanie stworzyć potężnego pałacu, czy szeregu sług. Niektórzy nazywają ją „rzeczywista iluzją”. Do rzucania zaklęć mag nie może być bardzo rozproszony, dlatego też magowie parający się tym rodzajem magii nie są dobrzy w bitwie, czy pojedynkach, gdyż praktycznie całe otoczenie może wpłynąć na zmianę ich myśli. Mimo tylu swoich ułomności, jest jedną z najbardziej pożądanych dziedzin magicznych. Wielu próbuje udoskonalać swoje twory, z różnym często skutkiem.
<br><br>- <b>Magia Światła</b> – jest to magia lecząca. Czarodzieje zajmujący się tą magią mogą leczyć rany, przywracać siły witalne (nie magiczne), a także ci potężniejsi, wskrzeszać. Mag światła nazywany jest potocznie Uzdrowicielem. Są to osoby często pobłogosławione przez bogów, mające dobroć w sercach. Nie jest to magia bojowa, chociaż sprytne wykorzystanie tego rodzaju magii może przechylić szalę zwycięstwa na Waszą stronę.
<br><br>- <b>Magia Ciemności</b> – tym mianem określamy całokształt magiczny, który obejmuje wszelakie zabawy z umarłymi, wysysanie życia, przyzywanie demonów. Nie jest to żaden chwalebny rodzaj magii, stąd też jest dość mocno tępiony wśród społeczności magicznej. Rozwój tej magii jest zakazany a wszelkie przejawy wzbogacenia zaklęć są często karane i piętnowane.
<br><br>- <b>Magia Run</b> – to ostatni rodzaj odkrytej w naszym świecie magii, jest ona stosunkowo młoda. Same runy są prawdopodobnie znacznie starsze, lecz zostały uznane za pismo starożytnych, stąd też jest nieczytelne dla wielu jej użytkowników.
<br><br>Runiczni magowie magią liter mogą obdarzać przeróżnymi zdolnościami, czy specyfikacjami, przedmioty jak i ludzi. Tych magów szanują najbardziej magowie oręża, gdyż tylko oni są w stanie zaklinać przedmioty, nadając im nowe magiczne właściwości. Jest to tez magia, która w dużym stopniu nie zależy od pojemności magicznej maga, a jedynie od jego wiedzy na temat pisma runicznego. Podstawowe zaklęcia runiczne dostępne są dla każdego maga, lecz są też bezużyteczne jeżeli chodzi o nadawanie potężnych właściwości. Bez znajomości odpowiedniego układu liter mag nie będzie w stanie obdarzyć miecza nieskończonym płomieniem, czy też nie będzie w stanie stworzyć dobrze działającego medalionu ochronnego. Magia pisma używana jest nie tylko do ulepszania przedmiotów, czy ludzi, ale też może być wykorzystywana jako wprawna magia bojowa, z ograniczeniem jedynie czasu jaki mag musi poświęcić na napisanie zaklęcia. Może on stworzyć ognisko, dość duży staw, przywołać armię łuczników, lecz to wszystko wymaga czasu na napisanie odpowiednio długiej inkantacji.
 <br>
<p>Pojemność magiczna fabularnie i mechanicznie (limity magiczne, ilość zaklęć)
</p><p>To wartość określająca ilość energii mogącej wypełnić ciało maga, lub przezeń przepłynąć w danym czasie. Jest ona zawsze określana skalą 10 punktową. Stąd też magowie szkolący się samodzielnie są w stanie osiągnąć co najwyżej 5 poziom pojemności, czyli ni mnie ni więcej a połowę swoich magicznych możliwości. Każdej postaci maga przysługuje po trzy znane zaklęcia na 10 poziomów, chyba, że liczba zaklęć zostanie nadana lub zwiększona w sesji fabularnej z Mistrzem Gry, co jest znacznie łatwiejszym rozwiązaniem.
</p><p>Nie istnieje żaden kanon tworzenia zaklęć, lecz jest on obarczony jedną zasadą: równoważnej mocy.
</p><p>Dlatego też magowie na podstawowym poziomie nie będą w stanie stworzyć zaklęcia, które będzie siało strach i zniszczenie. Zaś ci potężniejsi, wcale nie będą mogli tworzyć więcej zaklęć z poziomów niższych.
</p><p>Każde zaklęcie musi być zaakceptowane przez Mistrza Gry.
</p><br>
<b>Wzór opisu zaklęcia</b><br>
Nazwa: (Np. przyzwanie zbroi runicznego księżyca)<br>
Domena: (Np. Magia Oręża)<br>
Pojemność: (Twoja obecna pojemność magiczna, uprasza się o stałą kontrolę mocy i sukcesywną edycję)
<br>Inkantacja: (Mogą być to słowa w języku polskim, lub wymyślonym, nawiązujące do danej domeny)
<br>Opis zaklęcia: ( Jaki efekt wywołuje dane zaklęcie, im dokładniej opisany efekt, tym większa możliwość nietrafnej interpretacji przez Mistrza Gry podczas sesji)
<br>Ograniczenia: (Każde zaklęcie musi mieć swoje ograniczenia, np. możliwość rzucenia raz na dobę, lub np. działa tylko gdy pada deszcz, lub działa jedynie na 1 osobę)
<br>Sygnatura: (ID Mistrza Gry, który zezwolił na zaklęcie)
<br>

